##############################################
#                                            #
#              Aetheria Theme                #
#                                            #
##############################################

# This theme was created by: https://github.com/JJDizzl ! Thank you <3

# This contains the theme config file for superfile! For more details see:
# https://superfile.dev/configure/custom-theme/

###############################################################################
#                           Code Syntax Highlighting                          #
###############################################################################

# Find one you like at: https://github.com/alecthomas/chroma/blob/master/styles.

code_syntax_highlight = "catppuccin-macchiato"

###############################################################################
#                                 Base Colors                                 #
###############################################################################

#-- Full Screen
full_screen_fg = "#14B9B5"
full_screen_bg = "#0e091d"

#-- Gradient
# Note: This currently only supports two colors.
gradient_color = ["#14B9B5", "#A60234"]

#-- File Panel
file_panel_fg = "#14B9B5"
file_panel_bg = "#0e091d"
file_panel_border = "#A60234"
file_panel_border_active = "#BE3F50"
file_panel_top_directory_icon = "#000000"
file_panel_top_path = "#c53253"
file_panel_item_selected_fg = "#c53253"
file_panel_item_selected_bg = "#0e091d"

#-- Footer
footer_fg = "#14B9B5"
footer_bg = "#0e091d"
footer_border = "#BE3F50"
footer_border_active = "#BE3F50"

#-- Sidebar
sidebar_fg = "#14B9B5"
sidebar_bg = "#0e091d"
sidebar_title = "#11AEB3"
sidebar_border = "#A60234"
sidebar_border_active = "#BE3F50"
sidebar_item_selected_fg = "#c53253"
sidebar_item_selected_bg = "#0e091d"
sidebar_divider = "#A60234"

#-- Modals
modal_fg = "#14B9B5"
modal_bg = "#0e091d"
modal_border_active = "#BE3F50"
modal_cancel_fg = "#383838"
modal_cancel_bg = "#c8e967"
modal_confirm_fg = "#383838"
modal_confirm_bg = "#E20342"

#-- Help Menu
help_menu_hotkey = "#7dcfff"
help_menu_title = "#11AEB3"

#-- Special
cursor = "#14B9B5"
correct = "#E20342"
error = "#c8e967"
hint = "#FF7F41"
cancel = "#c8e967"
